# Generated by Django 4.2.1 on 2024-10-11 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kcb_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KcbDepartments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('department_name', models.CharField(max_length=255, unique=True)),
                ('department_code', models.CharField(choices=[('RB', 'RB'), ('CB', 'CB'), ('IB', 'IB'), ('CAB', 'CAB'), ('PB', 'PB'), ('TC', 'TC'), ('RM', 'RM'), ('CL', 'CL'), ('HR', 'HR'), ('ICT', 'ICT'), ('CS', 'CS'), ('MS', 'MS'), ('FA', 'FA'), ('OP', 'OP'), ('AI', 'AI')], default='', max_length=9000, unique=True)),
                ('department_description', models.CharField(blank=True, default='', max_length=9000, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': '03. Departments',
                'db_table': 'kcb_departments',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='KcbRegionalZonal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('zone_name', models.CharField(max_length=255, unique=True)),
                ('zone_code', models.CharField(choices=[('ZONE_01', 'ZONE_01'), ('ZONE_02', 'ZONE_02'), ('ZONE_03', 'ZONE_03'), ('ZONE_04', 'ZONE_04')], default='', max_length=9000, unique=True)),
                ('zone_description', models.CharField(blank=True, default='', max_length=9000, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': '02. Regional Zone',
                'db_table': 'kcb_regional_zonal',
                'ordering': ['-id'],
            },
        ),
    ]
