# Generated by Django 4.2.1 on 2024-10-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcb_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofiles',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('SCANNING_OFFICERS', 'SCANNING OFFICERS'), ('SCANNING_QC_OFFICERS', 'SCANNING QC OFFICERS')], default='', max_length=9000),
        ),
        migrations.AlterModelTable(
            name='forgotpasswordrequestusers',
            table='kcb_users_forgot_password_request',
        ),
        migrations.AlterModelTable(
            name='usersprofiles',
            table='kcb_user_profiles',
        ),
    ]
