# Generated by Django 4.2.1 on 2024-10-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcb_accounts', '0002_alter_usersprofiles_profile_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forgotpasswordrequestusers',
            options={'ordering': ['-id'], 'verbose_name_plural': 'FORGOT PASSWORD REQUESTS'},
        ),
        migrations.AlterModelOptions(
            name='usersprofiles',
            options={'ordering': ['-id'], 'verbose_name_plural': 'USER PROFILES'},
        ),
        migrations.RenameField(
            model_name='forgotpasswordrequestusers',
            old_name='primary_key',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='usersprofiles',
            old_name='primary_key',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='usersprofiles',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('ADMIN_PROFILE', 'ADMIN_PROFILE'), ('NORMAL_PROFILE', 'NORMAL_PROFILE')], default='', max_length=9000),
        ),
    ]
